# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21

# Mod Properties
mod_id=ezblocks
mod_name=EZ Blocks
version=1.0.0
group=dev.ezblocks
archives_base_name=ezblocks

# Dependencies
fabric_api_version=0.161.0+26.3
